use_frameworks!

target 'CoinMarketService_Example' do
  pod 'CoinMarketService', :path => '../'

  target 'CoinMarketService_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
